### ISSUE TITLE
mdm-resources referencing CatalogueItemDomainType that isn't available in mdm-core for Classifier

### ISSUE THREAD

**Issue by GBishop-PHSA** [MauroDataMapper/mdm-resources#35]
I've made a change locally to enable User & Group Access editing for Classifications in the mdm-ui. 

/src/app/classification/classification-details/classification-details.component.ts
```
toggleSecuritySection() {
-    this.messageService.toggleUserGroupAccess();
+    this.dialog.openSecurityAccess(this.classification, 'classifier');
}
```
After the above code change, I get a 400 error on requests to get the groupRoles and the securableGroupRoles when the User & Group Access modal is loading. 

When I update the mdm-resources to set the Classifier domaintype from 'Classification' to 'classifier', 
the requests return with 200. Should mdm-resources be updated to match the domainType in mdm-core?

mdm-core seems to set the Classifiers domainType here: 
https://github.com/MauroDataMapper/mdm-core/blob/18e0a40a8c77206e307cdade6715f720d06e1ce5/mdm-core/grails-app/domain/uk/ac/ox/softeng/maurodatamapper/core/container/Classifier.groovy#L94

mdm-resources sets the Classifiers CatalogueItemDomainType here: 
https://github.com/MauroDataMapper/mdm-resources/blob/57006ec4e3c65d3ff3cc6e57aaf209a66bc1f4d5/src/mdm-common.model.ts#L61

**Comment by olliefreeman** [comment]
im not a developer on mdm-resources but can i ask what the final URL is that mdm-resources calls?? out of curiosity

**Comment by GBishop-PHSA** [comment]
The mdm-resources builds the 2 requests and sends: 
/api/Classification/<classifier_uuid>/groupRoles/
/api/Classification/<classifier_uuid>/securableResourceGroupRoles/

but the mdm-core grails app expects these paths: 
/api/classifiers/<classifier_uuid>/groupRoles/
/api/classifiers/<classifier_uuid>/securableResourceGroupRoles/

**Comment by GBishop-PHSA** [comment]
Any update on this issue? gh-354 is blocked by this ticket.

**Comment by gammonpeter** [comment]
Updated Name
