### ISSUE TITLE
Re-organisation of code files

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-resources#65]
# Rationale

The `mdm-resources` library has grown significantly over time, resulting in all code listed under the `src` folder directly. This can make navigating the source code more cumbersome because of the lack of clear organisation.

My suggestion is to internally reorganise the code files into sub-folders, grouped by relevance/type. The keys parts of the codebase that must remain the same though are:

1. The `src/index.ts` must remain in place - though the imports it refers to can be changed to match the new sub-folders.
2. The `package.json` file must keep the `main` and `module` properties in the npm package - as these refer to the primary entry point for the library to be used downstream.

# Suggestion

One possible way to organise the files would be by type, e.g.:

```
src
   |- models
      |- data-model-resource
      |- terminology-resource
   |- admin
      |- admin-resource
   |- authentication
      |- session-resource
      |- security-resource
   |- catalogue
      |- tree-resource
      |- profiles-resource
   |- common
```

Also, files should be moved around the repo using the `git mv` command to maintain commit history.

**Comment by jamesrwelch** [comment]
I very much like this idea.

a) Can we use the same structure as the [Postman library](https://documenter.getpostman.com/view/9840589/UVC8BkkA)?
b) Could we (probably in the future) auto-generate any of the code from the postman library?

**Comment by pjmonks** [comment]
Following the same structure as the Postman library sounds like a good idea 👍
